CREATE TABLE "DB626"."AGENTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CREATED_DT" DATE NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"UPDATED_DT" DATE, 
	"UPDATED_BY" NUMBER, 
	"SPORT_ID" NUMBER DEFAULT NULL NOT NULL ENABLE, 
	 CONSTRAINT "AGENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "AGENTS_FK1" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE, 
	 CONSTRAINT "AGENTS_FK2" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."MANAGERS" ("ID") ENABLE, 
	 CONSTRAINT "AGENTS_FK3" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "DB626"."MANAGERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;