CREATE TABLE "DB626"."AGENT_ARTICLES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORT_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION1" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION2" VARCHAR2(4000 BYTE), 
	"DOCUMENT1" BLOB, 
	"DOCUMENT2" BLOB, 
	"IMAGE1" BLOB, 
	"POSTED_BY" NUMBER NOT NULL ENABLE, 
	"POSTED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "AGENT_ARTICLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "AGENT_ARTICLES_FK1" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE, 
	 CONSTRAINT "AGENT_ARTICLES_FK2" FOREIGN KEY ("POSTED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STUDENTS" 
 LOB ("DOCUMENT1") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("DOCUMENT2") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("IMAGE1") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;