CREATE TABLE "DB626"."FOOTBALL_PLAYERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COUNTRY" NUMBER NOT NULL ENABLE, 
	"GAMES_PLAYED" NUMBER NOT NULL ENABLE, 
	"GAMES_STARTED" NUMBER NOT NULL ENABLE, 
	"MINUTES_PLAYED" NUMBER NOT NULL ENABLE, 
	"GOALS" NUMBER NOT NULL ENABLE, 
	"ASSISTS" NUMBER NOT NULL ENABLE, 
	"SHOTS_ON_GOAL" NUMBER NOT NULL ENABLE, 
	"SHOTS" NUMBER NOT NULL ENABLE, 
	"YELLOW_CARDS" NUMBER NOT NULL ENABLE, 
	"RED_CARDS" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DT" TIMESTAMP (6), 
	 CONSTRAINT "FOOTBALL_PLAYERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "FOOTBALL_PLAYERS_FK1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "FOOTBALL_PLAYERS_FK2" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "FOOTBALL_PLAYERS_FK3" FOREIGN KEY ("COUNTRY")
	  REFERENCES "DB626"."COUNTRIES" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STUDENTS" ;