CREATE TABLE "DB626"."GOLF_PLAYERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COUNTRY" NUMBER NOT NULL ENABLE, 
	"EVENTS" NUMBER NOT NULL ENABLE, 
	"POINTS_GAINED" NUMBER NOT NULL ENABLE, 
	"POINTS_LOST" NUMBER NOT NULL ENABLE, 
	"STROKES_GAINED" NUMBER NOT NULL ENABLE, 
	"NO_OF_PUTTS" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DT" TIMESTAMP (6), 
	 CONSTRAINT "GOLF_PLAYERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "GOLF_PLAYERS_FK1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "GOLF_PLAYERS_FK2" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "GOLF_PLAYERS_FK3" FOREIGN KEY ("COUNTRY")
	  REFERENCES "DB626"."COUNTRIES" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STUDENTS" ;