CREATE TABLE "DB626"."NOTIFICATIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOTIFICATION" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"SPORT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "NOTIFICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "NOTIFICATIONS_FK1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "NOTIFICATIONS_FK2" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;