CREATE TABLE "DB626"."TICKET_VENDORS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TOURNAMENT_ID" NUMBER NOT NULL ENABLE, 
	"URL" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"UPDATED_DT" TIMESTAMP (6), 
	"UPDATED_BY" NUMBER, 
	 CONSTRAINT "TICKET_VENDORS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "TICKET_VENDORS_FK1" FOREIGN KEY ("TOURNAMENT_ID")
	  REFERENCES "DB626"."TOURNAMENTS" ("ID") ENABLE, 
	 CONSTRAINT "TICKET_VENDORS_FK2" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "TICKET_VENDORS_FK3" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "STUDENTS" ;