CREATE TABLE "DB626"."TOURNAMENTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"COUNTRY" NUMBER NOT NULL ENABLE, 
	"NO_OF_MATCHES" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DT" TIMESTAMP (6), 
	 CONSTRAINT "TOURNAMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "TOURNAMENTS_FK1" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "TOURNAMENTS_FK2" FOREIGN KEY ("UPDATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE, 
	 CONSTRAINT "TOURNAMENTS_FK3" FOREIGN KEY ("COUNTRY")
	  REFERENCES "DB626"."COUNTRIES" ("ID") ENABLE, 
	 CONSTRAINT "TOURNAMENTS_FK4" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;

  CREATE INDEX "DB626"."TOURNAMENTS_FN_IDX" ON "DB626"."TOURNAMENTS" (EXTRACT(YEAR FROM "START_DATE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;