CREATE TABLE "DB626"."USERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MIDDLE_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE_1" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"ADDRESS_LINE_2" VARCHAR2(200 BYTE), 
	"CITY" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COUNTRY" NUMBER NOT NULL ENABLE, 
	"ZIPCODE" NUMBER NOT NULL ENABLE, 
	"CONTACT" VARCHAR2(20 BYTE), 
	"EMAIL_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_DT" TIMESTAMP (6), 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "USERS_FK1" FOREIGN KEY ("COUNTRY")
	  REFERENCES "DB626"."COUNTRIES" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;