CREATE TABLE "DB626"."USERS_SPORTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"SPORT_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_SPORTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "USERS_SPORTS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "DB626"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "USERS_SPORTS_FK2" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;