CREATE TABLE "DB626"."USER_ARTICLES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SPORT_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION1" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION2" VARCHAR2(4000 BYTE), 
	"DOCUMENT1" BLOB, 
	"DOCUMENT2" BLOB, 
	"IMAGE1" BLOB, 
	"POSTED_BY" NUMBER NOT NULL ENABLE, 
	"POSTED_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"VALID_FLAG" CHAR(1 BYTE) NOT NULL ENABLE, 
	"VALIDATED_BY" NUMBER, 
	"VALIDATED_DT" TIMESTAMP (6), 
	 CONSTRAINT "USER_ARTICLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE, 
	 CONSTRAINT "USER_ARTICLES_CHK1" CHECK (VALID_FLAG IN ('Y','N')) ENABLE, 
	 CONSTRAINT "USER_ARTICLES_FK1" FOREIGN KEY ("SPORT_ID")
	  REFERENCES "DB626"."SPORTS" ("ID") ENABLE, 
	 CONSTRAINT "USER_ARTICLES_FK2" FOREIGN KEY ("POSTED_BY")
	  REFERENCES "DB626"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "USER_ARTICLES_FK3" FOREIGN KEY ("VALIDATED_BY")
	  REFERENCES "DB626"."AGENTS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" 
 LOB ("DOCUMENT1") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DOCUMENT2") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE1") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;